config/routes.rb
Rails.application.routes.draw do
  root 'urls#new'
  resources :urls

end

app/models/url.rb
class Url < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
    @url = Url.new
  end

  def create
    @url = Url.new(clean_params)
    puts clean_params
    @url.save
    redirect_to new_url_path(id: @url.id)
  end

  def show
    @url = Url.find(params[:id])
    redirect_to(@url.original_url)
  end

  def clean_params
    params.require(:url).permit(:original_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_helper.rb
module UrlHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tinyurl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/url/create.html.erb
<h1>Url#create</h1>
<p>Find me in app/views/url/create.html.erb</p>

app/views/urls/create.html.erb
<h1>Url#create</h1>
<%= @url.original_url %>

app/views/urls/new.html.erb
<h1>Urls</h1>
<%= form_for @url do |f| %>
  <%= f.label :original_url %><br>
  <%= f.text_field :original_url %>
  <%= f.submit %>
<% end %>
<%= url_url(params[:id]) if params[:id] %>

app/views/urls/show.html.erb
<h1>Url#show</h1>
<p>Find me in app/views/url/show.html.erb</p>